#!/usr/bin/env bash
#Prints numnbers from 1 to 20 in addition
#4 prints bad luck from china
#9 prints bad luck from Japan
#17 prints bad luck from Italy

counter=1

while [ $counter -le 20 ]
do
    echo "$counter"
    case $counter in
        "4") echo "bad luck from China";;
        "9") echo "bad luck from Japan";;
        "17") echo "bad luck from Italy";;
    esac
    (( counter++ ))
done
