#!/usr/bin/env bash
#Script that displays time for 12hours and 59 minutes
#hours form 0 to 12
#minutes from 1 to 59

hour=0

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]
    do
        echo "$minute"
        (( minute++ ))
    done
    (( hour++ ))
done
